# Generated by Django 3.1.4 on 2022-01-18 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsondata', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='hola',
        ),
        migrations.RenameField(
            model_name='hola',
            old_name='describtion',
            new_name='description',
        ),
    ]
