# Generated by Django 3.1.4 on 2022-01-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsondata', '0002_auto_20220118_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='jsoninfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_year', models.IntegerField()),
            ],
        ),
    ]
